/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as ArenaIndexRouteImport } from './routes/arena/index'
import { Route as WikiSlugRouteImport } from './routes/wiki/$slug'
import { Route as LessonSlugRouteImport } from './routes/lesson/$slug'
import { Route as LearnSoapRouteImport } from './routes/learn/soap'
import { Route as LearnRestRouteImport } from './routes/learn/rest'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaIndexRoute = ArenaIndexRouteImport.update({
  id: '/arena/',
  path: '/arena/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonSlugRoute = LessonSlugRouteImport.update({
  id: '/lesson/$slug',
  path: '/lesson/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSoapRoute = LearnSoapRouteImport.update({
  id: '/learn/soap',
  path: '/learn/soap',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRestRoute = LearnRestRouteImport.update({
  id: '/learn/rest',
  path: '/learn/rest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRoute
  '/settings': typeof SettingsRoute
  '/learn/rest': typeof LearnRestRoute
  '/learn/soap': typeof LearnSoapRoute
  '/lesson/$slug': typeof LessonSlugRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/arena/': typeof ArenaIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRoute
  '/settings': typeof SettingsRoute
  '/learn/rest': typeof LearnRestRoute
  '/learn/soap': typeof LearnSoapRoute
  '/lesson/$slug': typeof LessonSlugRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/arena': typeof ArenaIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRoute
  '/settings': typeof SettingsRoute
  '/learn/rest': typeof LearnRestRoute
  '/learn/soap': typeof LearnSoapRoute
  '/lesson/$slug': typeof LessonSlugRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/arena/': typeof ArenaIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/directory'
    | '/settings'
    | '/learn/rest'
    | '/learn/soap'
    | '/lesson/$slug'
    | '/wiki/$slug'
    | '/arena/'
    | '/wiki/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/directory'
    | '/settings'
    | '/learn/rest'
    | '/learn/soap'
    | '/lesson/$slug'
    | '/wiki/$slug'
    | '/arena'
    | '/wiki'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/directory'
    | '/settings'
    | '/learn/rest'
    | '/learn/soap'
    | '/lesson/$slug'
    | '/wiki/$slug'
    | '/arena/'
    | '/wiki/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectoryRoute: typeof DirectoryRoute
  SettingsRoute: typeof SettingsRoute
  LearnRestRoute: typeof LearnRestRoute
  LearnSoapRoute: typeof LearnSoapRoute
  LessonSlugRoute: typeof LessonSlugRoute
  WikiSlugRoute: typeof WikiSlugRoute
  ArenaIndexRoute: typeof ArenaIndexRoute
  WikiIndexRoute: typeof WikiIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/': {
      id: '/arena/'
      path: '/arena'
      fullPath: '/arena/'
      preLoaderRoute: typeof ArenaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$slug': {
      id: '/lesson/$slug'
      path: '/lesson/$slug'
      fullPath: '/lesson/$slug'
      preLoaderRoute: typeof LessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/soap': {
      id: '/learn/soap'
      path: '/learn/soap'
      fullPath: '/learn/soap'
      preLoaderRoute: typeof LearnSoapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/rest': {
      id: '/learn/rest'
      path: '/learn/rest'
      fullPath: '/learn/rest'
      preLoaderRoute: typeof LearnRestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectoryRoute: DirectoryRoute,
  SettingsRoute: SettingsRoute,
  LearnRestRoute: LearnRestRoute,
  LearnSoapRoute: LearnSoapRoute,
  LessonSlugRoute: LessonSlugRoute,
  WikiSlugRoute: WikiSlugRoute,
  ArenaIndexRoute: ArenaIndexRoute,
  WikiIndexRoute: WikiIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
